### PR TITLE
Make mUrlin Cacti 1.x compatible

### PR DESCRIPTION
**Pull request by thurban**
- Mostly changed the database calls to prepared statements 
- Removed old Code and changed include files to function calls

### CODE REVIEW

**Comment by netniV** [comment]
Is this ready to merge @thurban ?

**Comment by thurban** [comment]
Not yet. There seems to be a bug in the scripts/functions.php file which causes the plugin to be disabled. Still need to find that issue.

I also have a version that uses the local_db_conn even for remote pollers for accessing the plugin related database tables.  Still need to convert the related "full sync" command for the database tables to the code

**Comment by netniV** [comment]
If you want to merge what you have, I can look at the function problem?

**Comment by netniV** [comment]
After all, this isn't a functional plugin yet ;-)

**Pull request merged**
